---
alexa_client:
  id: "{{ lookup('pipe', 'op read op://ansible/Alexa/username') }}"
  secret: "{{ lookup('pipe', 'op read op://ansible/Alexa/credential') }}"
card_mod_version: 4.1.0
frosted_glass_manager_version: 1.3
frosted_glass_version: 1.3
gmail:
  address: "{{ lookup('pipe', 'op read op://ansible/Gmail/username') }}"
  password: "{{ lookup('pipe', 'op read op://ansible/Gmail/credential') }}"
homeassistant_token: "{{ lookup('pipe', 'op read \"op://ansible/Home Assistant/token\"') }}"
latlng:
  home:
    lat: "{{ lookup('pipe', 'op read \"op://ansible/Tats Shibata/latitude\"') }}"
    lng: "{{ lookup('pipe', 'op read \"op://ansible/Tats Shibata/longitude\"') }}"
mini_graph_card_version: 0.13.0
mini_media_player_version: 1.16.9
mosquitto_password: "{{ lookup('pipe', 'op read op://ansible/Mosquitto/credential') }}"
postgres:
  username: "{{ lookup('pipe', 'op read \"op://ansible/PostgreSQL - Home Assistant/username\"') }}"
  password: "{{ lookup('pipe', 'op read \"op://ansible/PostgreSQL - Home Assistant/password\"') }}"
  hostname: "{{ lookup('pipe', 'op read \"op://ansible/PostgreSQL - Home Assistant/server\"') }}"
  db: "{{ lookup('pipe', 'op read \"op://ansible/PostgreSQL - Home Assistant/database\"') }}"
regza:
  username: "{{ lookup('pipe', 'op read op://ansible/REGZA/username') }}"
  password: "{{ lookup('pipe', 'op read op://ansible/REGZA/credential') }}"
simple_thermostat_version: 2.5.0
simple_weather_card_version: 0.8.5
tuya_local_version: 2026.2.0
