---
- name: "Reload systemd"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "enecoq-data-fetcher : Restart timer"
  ansible.builtin.systemd:
    name: enecoq-data-fetcher.timer
    state: restarted
    daemon_reload: true
