---
- name: "ipv6-mtu : Create on_boot.d directory"
  ansible.builtin.file:
    path: /data/on_boot.d
    state: directory
    mode: '0755'
  tags:
    - udm
    - config
    - udm_ipv6-mtu
    - udm_ipv6-mtu_init

- name: "ipv6-mtu : Copy boot script"
  ansible.builtin.copy:
    src: 20-ipv6-mtu.sh
    dest: /data/on_boot.d/20-ipv6-mtu.sh
    mode: '0755'
  tags:
    - udm
    - config
    - udm_ipv6-mtu
    - udm_ipv6-mtu_config

- name: "ipv6-mtu : Apply configuration"
  ansible.builtin.command: /data/on_boot.d/20-ipv6-mtu.sh
  tags:
    - udm
    - config
    - udm_ipv6-mtu
    - udm_ipv6-mtu_config
