---
relayhost:
  name: smtp.mail.us-west-2.awsapps.com
  port: 465
workmail:
  username: "{{ lookup('pipe', 'op read op://ansible/WorkMail/username') }}"
  password: "{{ lookup('pipe', 'op read op://ansible/WorkMail/credential') }}"
