---
fukasawa_version: 2.1.3
php_version: 8.3
wordpress:
  db_password: "{{ lookup('pipe', 'op read \"op://ansible/MySQL - WordPress/password\"') }}"
  auth_key: "{{ lookup('pipe', 'op read \"op://ansible/WordPress/username\"') }}"
  secure_auth_key: "{{ lookup('pipe', 'op read \"op://ansible/WordPress/credential\"') }}"
  logged_in_key: "{{ lookup('pipe', 'op read \"op://ansible/WordPress/logged in key\"') }}"
  nonce_key: "{{ lookup('pipe', 'op read \"op://ansible/WordPress/nonce key\"') }}"
  auth_salt: "{{ lookup('pipe', 'op read \"op://ansible/WordPress/auth salt\"') }}"
  secure_auth_salt: "{{ lookup('pipe', 'op read \"op://ansible/WordPress/secure auth salt\"') }}"
  logged_in_salt: "{{ lookup('pipe', 'op read \"op://ansible/WordPress/logged in salt\"') }}"
  nonce_salt: "{{ lookup('pipe', 'op read \"op://ansible/WordPress/nonce salt\"') }}"
