---
mysql_apt_config_version: 0.8.34-1
mysql_connector_version: 9.6.0-1ubuntu24.04
oracle_instantclient_version_1: 23
oracle_instantclient_version_2: 26
oracle_instantclient_version_3: 1
oracle_instantclient_version_4: 0
oracle_instantclient_version_5: 0
redshift_jdbc_version: 2.1.0.21
