---
- name: "apache: Restart"
  ansible.builtin.systemd:
    name: apache2
    state: restarted

- name: "apache: Reload"
  ansible.builtin.systemd:
    name: apache2
    state: reloaded

- name: "zabbix-server: Restart"
  ansible.builtin.systemd:
    name: zabbix-server
    state: restarted
