---
- name: Restart apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted

- name: Reload apache
  ansible.builtin.systemd:
    name: apache2
    state: reloaded

- name: Restart zabbix-server
  ansible.builtin.systemd:
    name: zabbix-server
    state: restarted
