---
mcp_servers_business:
  awslabs.aws-api-mcp-server:
    command: "uvx"
    args:
      - "awslabs.aws-api-mcp-server@latest"
    disabled: true
    autoApprove: []
  awslabs.aws-documentation-mcp-server:
    command: "uvx"
    args:
      - "awslabs.aws-documentation-mcp-server@latest"
    disabled: true
    autoApprove: []
  aws-knowledge-mcp-server:
    command: "uvx"
    args:
      - "fastmcp"
      - "run"
      - "https://knowledge-mcp.global.api.aws"
    disabled: true
    autoApprove: []
