---
zabbix:
  db_host: "{{ lookup('pipe', 'op read \"op://ansible/PostgreSQL - Zabbix/server\"') }}"
  db_password: "{{ lookup('pipe', 'op read \"op://ansible/PostgreSQL - Zabbix/password\"') }}"
  version: 7.4
