# Dad’s Room

dads_room_climate_mode:
  name: "Dad’s Room Climate Mode"
  options:
    - "Present Summer"
    - "Present Winter"
    - "Present Summer Midnight"
    - "Present Winter Midnight"
    - "Absent Summer"
    - "Absent Winter"
  icon: "mdi:thermostat-auto"
dads_room_light_mode:
  name: "Dad’s Room Light Mode"
  options:
    - "Turned on Daytime"
    - "Turned on Twilight"
    - "Turned on Night"
    - "Turned on Late Night"
    - "Turned on Midnight"
    - "Daytime"
    - "Twilight"
    - "Night"
    - "Late Night"
    - "Midnight"
    - "Dark"
  icon: "mdi:lightbulb-auto"
dads_room_light_remote_mode:
  name: "Dad’s Room Light Remote Mode"
  options:
    - "Turned on"
    - "Turned off"
    - "Idle"
  icon: "mdi:remote"
dads_room_scene:
  name: "Dad’s Room Scene"
  options:
    - "scene.dads_room_bright"
    - "scene.dads_room_dimmed"
    - "scene.dads_room_arise"
    - "scene.dads_room_shine"
    - "scene.dads_room_storybook"
    - "scene.dads_room_unwind"
    - "scene.dads_room_nighttime"
    - "scene.dads_room_blossom"
    - "scene.dads_room_crocus"
    - "scene.dads_room_starlight"
    - "scene.dads_room_energize"
    - "scene.dads_room_concentrate"
    - "scene.dads_room_read"
    - "scene.dads_room_dimmed_read"
    - "scene.dads_room_relax"
    - "scene.dads_room_rest"
    - "scene.dads_room_nightlight"
    - "scene.dads_room_city_of_love"
    - "scene.dads_room_dark"
  icon: "mdi:form-select"
dads_room_scene_daytime:
  name: "Dad’s Room Scene Daytime"
  options:
    - "scene.dads_room_bright"
    - "scene.dads_room_dimmed"
    - "scene.dads_room_arise"
    - "scene.dads_room_shine"
    - "scene.dads_room_storybook"
    - "scene.dads_room_unwind"
    - "scene.dads_room_nighttime"
    - "scene.dads_room_blossom"
    - "scene.dads_room_crocus"
    - "scene.dads_room_starlight"
    - "scene.dads_room_energize"
    - "scene.dads_room_concentrate"
    - "scene.dads_room_read"
    - "scene.dads_room_dimmed_read"
    - "scene.dads_room_relax"
    - "scene.dads_room_rest"
    - "scene.dads_room_nightlight"
    - "scene.dads_room_city_of_love"
    - "scene.dads_room_dark"
  icon: "mdi:weather-sunny"
dads_room_scene_night:
  name: "Dad’s Room Scene Night"
  options:
    - "scene.dads_room_bright"
    - "scene.dads_room_dimmed"
    - "scene.dads_room_arise"
    - "scene.dads_room_shine"
    - "scene.dads_room_storybook"
    - "scene.dads_room_unwind"
    - "scene.dads_room_nighttime"
    - "scene.dads_room_blossom"
    - "scene.dads_room_crocus"
    - "scene.dads_room_starlight"
    - "scene.dads_room_energize"
    - "scene.dads_room_concentrate"
    - "scene.dads_room_read"
    - "scene.dads_room_dimmed_read"
    - "scene.dads_room_relax"
    - "scene.dads_room_rest"
    - "scene.dads_room_nightlight"
    - "scene.dads_room_city_of_love"
    - "scene.dads_room_dark"
  icon: "mdi:weather-night"
dads_room_scene_late_night:
  name: "Dad’s Room Scene Late Night"
  options:
    - "scene.dads_room_bright"
    - "scene.dads_room_dimmed"
    - "scene.dads_room_arise"
    - "scene.dads_room_shine"
    - "scene.dads_room_storybook"
    - "scene.dads_room_unwind"
    - "scene.dads_room_nighttime"
    - "scene.dads_room_blossom"
    - "scene.dads_room_crocus"
    - "scene.dads_room_starlight"
    - "scene.dads_room_energize"
    - "scene.dads_room_concentrate"
    - "scene.dads_room_read"
    - "scene.dads_room_dimmed_read"
    - "scene.dads_room_relax"
    - "scene.dads_room_rest"
    - "scene.dads_room_nightlight"
    - "scene.dads_room_city_of_love"
    - "scene.dads_room_dark"
  icon: "mdi:brightness-2"
dads_room_scene_midnight:
  name: "Dad’s Room Scene Midnight"
  options:
    - "scene.dads_room_bright"
    - "scene.dads_room_dimmed"
    - "scene.dads_room_arise"
    - "scene.dads_room_shine"
    - "scene.dads_room_storybook"
    - "scene.dads_room_unwind"
    - "scene.dads_room_nighttime"
    - "scene.dads_room_blossom"
    - "scene.dads_room_crocus"
    - "scene.dads_room_starlight"
    - "scene.dads_room_energize"
    - "scene.dads_room_concentrate"
    - "scene.dads_room_read"
    - "scene.dads_room_dimmed_read"
    - "scene.dads_room_relax"
    - "scene.dads_room_rest"
    - "scene.dads_room_nightlight"
    - "scene.dads_room_city_of_love"
    - "scene.dads_room_dark"
  icon: "mdi:brightness-3"

# Living Room

living_room_climate_mode:
  name: "Living Room Climate Mode"
  options:
    - "Present Summer"
    - "Present Winter"
    - "Present Summer Midnight"
    - "Present Winter Midnight"
    - "Absent Summer"
    - "Absent Winter"
    - "Ventilated"
  icon: "mdi:thermostat-auto"
living_room_light_mode:
  name: "Living Room Light Mode"
  options:
    - "Daytime"
    - "Twilight"
    - "Night"
    - "Late Night"
    - "Midnight"
    - "Dark"
  icon: "mdi:lightbulb-auto"
living_room_regza_content_type_mode:
  name: "Living Room Regza Content Type Mode"
  options:
    - "Internal"
    - "External"
    - "Off"
  icon: "mdi:video-input-hdmi"
living_room_scene:
  name: "Living Room Scene"
  options:
    - "scene.living_room_daytime"
    - "scene.living_room_twilight"
    - "scene.living_room_night"
    - "scene.living_room_late_night"
    - "scene.living_room_midnight"
    - "scene.living_room_dark"
  icon: "mdi:form-select"
moms_room_climate_mode:
  name: "Mom’s Room Climate Mode"
  options:
    - "Present Summer"
    - "Present Winter"
    - "Present Summer Midnight"
    - "Present Winter Midnight"
    - "Absent Summer"
    - "Absent Winter"
    - "Ventilated"
  icon: "mdi:thermostat-auto"

# Mom’s Room

moms_room_light_mode:
  name: "Mom’s Room Light Mode"
  options:
    - "Turned on Daytime"
    - "Turned on Twilight"
    - "Turned on Night"
    - "Turned on Late Night"
    - "Turned on Midnight"
    - "Daytime"
    - "Twilight"
    - "Night"
    - "Late Night"
    - "Midnight"
    - "Dark"
  icon: "mdi:lightbulb-auto"
moms_room_light_remote_mode:
  name: "Mom’s Room Light Remote Mode"
  options:
    - "Turned on"
    - "Turned off"
    - "Idle"
  icon: "mdi:remote"
moms_room_scene:
  name: "Mom’s Room Scene"
  options:
    - "scene.moms_room_bright"
    - "scene.moms_room_nightlight"
    - "scene.moms_room_relax"
    - "scene.moms_room_rest"
    - "scene.moms_room_dark"
  icon: "mdi:form-select"
moms_room_scene_daytime:
  name: "Mom’s Room Scene Daytime"
  options:
    - "scene.moms_room_bright"
    - "scene.moms_room_nightlight"
    - "scene.moms_room_relax"
    - "scene.moms_room_rest"
    - "scene.moms_room_dark"
  icon: "mdi:weather-sunny"
moms_room_scene_night:
  name: "Mom’s Room Scene Night"
  options:
    - "scene.moms_room_bright"
    - "scene.moms_room_nightlight"
    - "scene.moms_room_relax"
    - "scene.moms_room_rest"
    - "scene.moms_room_dark"
  icon: "mdi:weather-night"
moms_room_scene_late_night:
  name: "Mom’s Room Scene Late Night"
  options:
    - "scene.moms_room_bright"
    - "scene.moms_room_nightlight"
    - "scene.moms_room_relax"
    - "scene.moms_room_rest"
    - "scene.moms_room_dark"
  icon: "mdi:brightness-2"
moms_room_scene_midnight:
  name: "Mom’s Room Scene Midnight"
  options:
    - "scene.moms_room_bright"
    - "scene.moms_room_nightlight"
    - "scene.moms_room_relax"
    - "scene.moms_room_rest"
    - "scene.moms_room_dark"
  icon: "mdi:brightness-3"

# Bathroom

bathroom_light_mode:
  name: "Bathroom Light Mode"
  options:
    - "Turned on Arise"
    - "Turned on Natural Light"
    - "Dark"
  icon: "mdi:lightbulb-auto"
bathroom_light_remote_mode:
  name: "Bathroom Light Remote Mode"
  options:
    - "Turned on"
    - "Turned off"
    - "Idle"
  icon: "mdi:remote"
bathroom_scene:
  name: "Bathroom Scene"
  options:
    - "scene.bathroom_arise"
    - "scene.bathroom_natural_light"
    - "scene.bathroom_dark"
  icon: "mdi:form-select"

# Season Mode

season_mode:
  name: "Season Mode"
  options:
    - "Summer"
    - "Winter"
  icon: "mdi:sun-snowflake-variant"

# Time Mode

time_mode:
  name: "Time Mode"
  options:
    - "Daytime"
    - "Twilight"
    - "Night"
    - "Late Night"
    - "Midnight"
  icon: "mdi:sun-clock"
