enecoq_co2_emission_daily:
  unique_id: sensor.enecoq_co2_emission_daily
  source: sensor.enecoq_co2_emission
  cycle: daily
enecoq_power_cost_daily:
  unique_id: sensor.enecoq_power_cost_daily
  source: sensor.enecoq_power_cost
  cycle: daily
enecoq_power_usage_daily:
  unique_id: sensor.enecoq_power_usage_daily
  source: sensor.enecoq_power_usage
  cycle: daily
enecoq_co2_emission_hourly:
  unique_id: sensor.enecoq_co2_emission_hourly
  source: sensor.enecoq_co2_emission
  cycle: hourly
enecoq_power_cost_hourly:
  unique_id: sensor.enecoq_power_cost_hourly
  source: sensor.enecoq_power_cost
  cycle: hourly
enecoq_power_usage_hourly:
  unique_id: sensor.enecoq_power_usage_hourly
  source: sensor.enecoq_power_usage
  cycle: hourly
