enecoq_monthly_low:
  unique_id: sensor.enecoq_monthly_low
  name: "enecoQ Monthly Low"
  source: sensor.enecoq_daily_low
  cycle: monthly
enecoq_monthly_mid:
  unique_id: sensor.enecoq_monthly_mid
  name: "enecoQ Monthly Mid"
  source: sensor.enecoq_daily_mid
  cycle: monthly
enecoq_monthly_high:
  unique_id: sensor.enecoq_monthly_high
  name: "enecoQ Monthly High"
  source: sensor.enecoq_daily_high
  cycle: monthly
enecoq_monthly_total:
  unique_id: sensor.enecoq_monthly_total
  name: "enecoQ Monthly Total"
  source: sensor.enecoq_daily_total
  cycle: monthly
